### PR TITLE
add troubleshooting section release update

### PR DESCRIPTION
**Pull request by plotters**

### CODE REVIEW

**Comment by oetiker** [comment]
Hi @plotters 
thanks for your PR ... may I ask you to create separate prs for separate issues in the future as is simplifies the review process.

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
@plotters I applied your dark mode settings to the website ... the effects are pretty fatal ... care to do an additional PR or should we revert ?

image

**Comment by oninoshiko** [comment]
I mentioned this on IRC, but I would respectfully request we go ahead and roll this back, and split the CSS changes out. they can be kept separate until they can be finished and more thoroughly tested. 

I definitely support adding dark-mode, but this just isn't complete yet.

**Comment by citrus-it** [comment]
I have reverted the two commits that changed the CSS for now.

**Pull request merged**
