### PR TITLE
About additions

### PR DESCRIPTION
**Pull request by rich-murphey**

### CODE REVIEW

**Comment by rich-murphey** [comment]
I can appreciate that there are sensitive subjects here, so please use whatever parts of this if you find any appropriate.  It might create some good will, not just with OmniTI but with the future community, to recognize by name individual OmniTI developers who contributed to OmniOS.

**Comment by oetiker** [comment]
@rich-murphey I like your additions ... since the website just has undergone some major surgery. can you please update your PR accordingly?

**Comment by rich-murphey** [comment]
I believe this changes only the body of about.md.  Just let me know if it's not in correct form!

**Comment by oetiker** [comment]
thanks!

**Pull request merged**
